const AR='٠١٢٣٤٥٦٧٨٩';
const toAr=n=>String(n).replace(/\d/g,d=>AR[d]);
const en=s=>String(s).replace(/[٠-٩]/g,d=>AR.indexOf(d));
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const KEY='rabt-items-v6';
let IMG='', IS_TEACHER=false;
const ADMIN_EMAILS=['k100ed10@gmail.com'];
const FB_CFG=Object.assign({apiKey:"",authDomain:"grade12platform.firebaseapp.com",projectId:"grade12platform",storageBucket:"grade12platform.firebasestorage.app",messagingSenderId:"",appId:""}, window.FIREBASE_CONFIG||{});
let fbDb=null, fbAuth=null;
function initFb(){try{if(!window.firebase)return;if(!FB_CFG.apiKey)return;if(!firebase.apps.length)firebase.initializeApp(FB_CFG);fbDb=firebase.firestore();fbAuth=firebase.auth();fbAuth.onAuthStateChanged(async u=>{if(u){await applyUser(u);}else{showLogin();}});}catch(e){console.warn(e)}}
function deviceId(){let id=localStorage.getItem('rabt-device');if(!id){id='d-'+Math.random().toString(36).slice(2)+Date.now().toString(36);localStorage.setItem('rabt-device',id);}return id;}
function showErr(msg){const e=$('#err');e.textContent=msg;e.style.display='block';}
let PENDING_NAME='';
function isTeacherAccount(email,data){const e=(email||'').toLowerCase();if(ADMIN_EMAILS.includes(e))return true;const role=String((data&&(data.role||data.type))||'').toLowerCase();return ['teacher','admin','معلم','مدير'].includes(role)||(data&&data.isTeacher===true);}
async function findUserDoc(u){const email=(u.email||'').toLowerCase();let ref=fbDb.collection('users').doc(u.uid);let snap=await ref.get();if(snap.exists) return {ref,data:snap.data()||{}};const q=await fbDb.collection('users').where('email','==',email).limit(1).get();if(!q.empty) return {ref:q.docs[0].ref,data:q.docs[0].data()||{}};return {ref,data:null};}
async function applyUser(u){IS_TEACHER=false;try{if(!fbDb){enterApp();return;}const found=await findUserDoc(u);let data=found.data||{};const email=(u.email||'').toLowerCase();IS_TEACHER=isTeacherAccount(email,data);const did=deviceId();let devices=Array.isArray(data.devices)?data.devices.slice():[];devices=devices.map(x=>typeof x==='string'?x:(x&&x.id)||'').filter(Boolean);if(devices.indexOf(did)===-1) devices.push(did);if(devices.length>40) devices=devices.slice(-40);const nm=PENDING_NAME||localStorage.getItem('rabt-name')||data.name||'';await found.ref.set({email:email,name:nm,role:IS_TEACHER?'teacher':'student',devices:devices,updated:Date.now()},{merge:true});enterApp();}catch(e){console.warn(e);enterApp();}}
function showLogin(){IS_TEACHER=false;$('#app').classList.add('hidden');$('#login').classList.remove('hidden');}
function authErr(c){const m={'auth/invalid-email':'البريد غير صالح','auth/user-not-found':'هذا البريد غير مسجّل','auth/wrong-password':'كلمة المرور غير صحيحة','auth/invalid-credential':'البريد أو كلمة المرور غير صحيحة','auth/too-many-requests':'محاولات كثيرة'};return m[c]||'تعذر الدخول';}
const UNIT={title:'الوحدة الأولى: القياس الدائري', lessons:[{id:'1-1',title:'١-١ الراديان',page:'١١'},{id:'1-2',title:'١-٢ طول القوس',page:'١٥'},{id:'1-3',title:'١-٣ مساحة القطاع الدائري',page:'١٨'}]};
function F(a,b){return '<span class="frac"><span class="num">'+a+'</span><span class="den">'+b+'</span></span>'}
function fracify(s){s=String(s==null?'':s);s=s.replace(/½/g,F('١','٢')).replace(/¼/g,F('١','٤'));s=s.replace(/π\s*\/\s*([٠-٩0-9]+)/g,(m,b)=>F('π',b));s=s.replace(/([٠-٩0-9]+)\s*\/\s*([٠-٩0-9]+)/g,(m,a,b)=>F(a,b));return s;}
function bankItems(){const meta=window.RABT_META||{};return (window.RABT_BANK||[]).map((q,i)=>{const m=meta[q.kind]||{};return {id:'bank-'+i,ex:q.ex,letter:q.letter,text:q.text,type:m.type||'tanwee',idea:m.idea||'بدون فكرة',steps:m.steps||'',required:m.required||'',kind:q.kind,lesson:m.lesson||'1-1',img:''};});}
function load(){const bank=bankItems();try{let a=JSON.parse(localStorage.getItem(KEY)||'[]');if(a.length<bank.length){a=bank.concat(a.filter(x=>String(x.id).startsWith('u')));localStorage.setItem(KEY,JSON.stringify(a))}return a.length?a:bank;}catch(e){return bank}}
function saveAll(a){localStorage.setItem(KEY,JSON.stringify(a))}
function openM(id){$('#'+id).classList.remove('hidden')} function closeM(id){$('#'+id).classList.add('hidden')}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),1500)}
function stats(items){$('#nAll').textContent=toAr(items.length);$('#nNew').textContent=toAr(items.filter(x=>x.type==='idea').length);$('#nTan').textContent=toAr(items.filter(x=>x.type==='tanwee').length);$('#nIdea').textContent=toAr([...new Set(items.map(x=>x.idea).filter(Boolean))].length);$('#nBadge').textContent=toAr(items.length)}
function givenOf(p){return p.given||p.text||'—'}
function showView(name){$$('.view').forEach(v=>v.classList.remove('on'));$('#view-'+name).classList.add('on');$$('nav [data-view]').forEach(b=>b.classList.toggle('on',b.dataset.view===name));$('#topBar').classList.toggle('hidden', name==='book');if(name==='book') $('#bookFrame').src='activity.html?v=3&t='+Date.now();}
function enterApp(){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');const shown=localStorage.getItem('rabt-name')||'';if(IS_TEACHER){$('#btnAdd').classList.remove('hidden');$('#who').textContent=shown||'حساب المعلم'}else{$('#btnAdd').classList.add('hidden');$('#who').textContent=shown||'حساب الطالب'}showView('home');render()}
function render(){const items=load();stats(items);let html='<details class="acc" open><summary><span>'+UNIT.title+'</span><span class="badge">'+toAr(items.length)+'</span></summary>';UNIT.lessons.forEach((ls,i)=>{const arr=items.filter(p=>(p.lesson||'1-1')===ls.id);html+='<details class="acc ls"'+(i===0?' open':'')+'><summary><span>'+ls.title+'</span><small>ص '+ls.page+'</small></summary>';if(!arr.length) html+='<div class="empty">لا توجد أفكار بعد</div>';else{const ideas=new Map();arr.forEach(p=>{const k=p.idea||'بدون فكرة';if(!ideas.has(k))ideas.set(k,[]);ideas.get(k).push(p)});ideas.forEach((qs,idea)=>{html+='<details class="acc id"><summary><span>'+fracify(idea)+'</span><span class="badge">'+toAr(qs.length)+'</span></summary><div class="qlist">';qs.forEach(p=>{html+='<button type="button" class="qnum" data-id="'+p.id+'">سؤال '+p.ex+' — '+(p.letter||'—')+'</button>';});html+='</div></details>';});}html+='</details>';});html+='</details>';$('#homeCards').innerHTML=html;$$('#homeCards .qnum').forEach(b=>b.onclick=()=>{const p=load().find(x=>String(x.id)===b.dataset.id);if(p)showQ(p)});}
function showQ(p){const neu=p.type==='idea';const card=$('#popCard');card.className='qcard'+(neu?' gold':'');card.innerHTML='<div class="qhead"><span class="kindtag '+(neu?'n':'t')+'">'+(neu?'★ فكرة جديدة':'تنويع')+'</span><div style="display:flex;gap:8px;align-items:center"><small>سؤال '+p.ex+' — '+p.letter+'</small><button class="x" id="popX">×</button></div></div>'+(p.img?'<img class="qimg" src="'+p.img+'">':'')+'<div class="qtxt">'+fracify(p.text)+'</div><div class="slots"><button type="button" class="slot s-idea" data-k="idea">الفكرة</button><button type="button" class="slot s-given" data-k="given">المعطيات</button><button type="button" class="slot s-steps" data-k="steps">الخطوات</button><button type="button" class="slot s-req" data-k="req">المطلوب</button></div><div class="slotbox hidden" id="slotBox"></div>';const map={idea:[fracify(p.idea||'—'),'idea'],given:[fracify(givenOf(p)),'given'],steps:[fracify(p.steps||'—'),'steps'],req:[fracify(p.required||'—'),'req']};const titles={idea:'الفكرة',given:'المعطيات',steps:'الخطوات',req:'المطلوب'};const box=$('#slotBox');card.querySelectorAll('.slot').forEach(s=>s.onclick=()=>{const on=s.classList.contains('on');card.querySelectorAll('.slot').forEach(x=>x.classList.remove('on'));if(on){box.classList.add('hidden');return}s.classList.add('on');box.classList.remove('hidden');const k=s.dataset.k;box.className='slotbox '+map[k][1];box.innerHTML='<b>'+titles[k]+'</b><br>'+map[k][0];});$('#popX').onclick=()=>$('#pop').classList.add('hidden');$('#pop').classList.remove('hidden');}
$('#loginBtn').onclick=async()=>{const email=$('#email').value.trim(),pass=$('#pass').value,name=$('#sname').value.trim();$('#err').style.display='none';if(!name||!email||!pass){$('#err').textContent='أدخل الاسم والبريد وكلمة المرور';$('#err').style.display='block';return}PENDING_NAME=name;localStorage.setItem('rabt-name',name);if(!fbAuth)initFb();if(!fbAuth){$('#err').textContent='Firebase غير جاهز';$('#err').style.display='block';return}try{await fbAuth.signInWithEmailAndPassword(email,pass);}catch(e){$('#err').textContent=authErr(e.code);$('#err').style.display='block';}};
$('#pass').addEventListener('keydown',e=>{if(e.key==='Enter')$("#loginBtn").click()});
$$('nav [data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$('#out').onclick=()=>{if(fbAuth)fbAuth.signOut();else showLogin();};
$('#btnAdd').onclick=()=>{if(!IS_TEACHER){toast('الإضافة للمعلم فقط');return}openM('addM')};
$$('[data-close]').forEach(b=>b.onclick=()=>closeM(b.dataset.close));
$('#pop').onclick=e=>{if(e.target.id==='pop')$("#pop").classList.add('hidden')};
$('#ptxt').addEventListener('input',()=>{$('#pcnt').textContent=toAr($('#ptxt').value.length)});
$$('.chip').forEach(c=>c.onclick=()=>{$('#pidea').value=c.dataset.idea});
$('#pimg').onchange=e=>{const f=e.target.files&&e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{IMG=r.result;$('#pprev').src=IMG;$('#pprev').classList.remove('hidden')};r.readAsDataURL(f)};
$('#save').onclick=()=>{if(!IS_TEACHER){toast('الإضافة للمعلم فقط');return}const text=$('#ptxt').value.trim();if(!text&&!IMG){toast('اكتب النص أو ارفع صورة');return}const a=load();a.push({id:'u'+Date.now(),ex:toAr(a.filter(x=>x.lesson===$('#plesson').value).length+1),letter:'—',text,type:$('#pnew').checked?'idea':'tanwee',idea:$('#pidea').value.trim()||'فكرة مضافة',given:$('#pgiven').value.trim(),steps:$('#psteps').value.trim(),required:$('#preq').value.trim(),lesson:$('#plesson').value,img:IMG});saveAll(a);IMG='';$('#pprev').classList.add('hidden');$('#ptxt').value='';closeM('addM');render();toast('أُضيفت في الدرس');};
initFb();
